### ISSUE TITLE
Firefox - Extension "Bring back YouTube Comment Usernames" broken since today (2024.11.17)

### ISSUE THREAD

**Issue by Miss-Toki** [Frank0945/return-yt-comment-usernames#1]
Hello,

I am using Firefox. The extension stopped working since today despite refreshes and turned on.
https://addons.mozilla.org/ja/firefox/addon/youtube-找回留言區用戶名稱/

Example: https://www.youtube.com/watch?v=vq3nWnTkFbk

![image](https://github.com/user-attachments/assets/aa454f8a-5590-4836-8623-2783b06263a6)

**Comment by Frank0945** [comment]
Unfortunately, I cannot replicate your situation.
However, I have released an updated version to address some potential issues (which previously only occurred in Chromium-based browsers).
I'm not sure if this is the cause of your issue, but please give it a try and see if it resolves the problem.

**Comment by Miss-Toki** [comment]
Unfortunately, the issue is still not resolved for me. I use Firefox Developer Edition 133.0b9 (64 ビット)

**Comment by Miss-Toki** [comment]
EDIT : For unknown reasons, the bug disappeared and the extension works correctly again since today.
So I terminated my ticket.

**Comment by Frank0945** [comment]
It might be due to sending too many requests (when fetching channel data), causing YouTube to temporarily block your client. I haven’t experienced this myself, but it seems plausible.
If I manage to reproduce the issue and find a solution, I will provide an update.
